name: CI
on:
  pull_request:
  push:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run checks
        run: |
          cargo check --examples --tests
          cargo fmt --all -- --check
          cargo clippy --examples --tests -- -D warnings
          cargo test
          cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
